### ISSUE TITLE
Issues with Paths on Windows

### ISSUE THREAD

**Issue by meng-hui** [unity3d-jp/AssetGraph#1]
In a Windows environment, using `Path.Combine` will return something like `Assets/Data\Test\Model`. This can be resolved by using `Path.GetFullPath`.

Also, there is a `UNITY_FOLDER_SEPARATOR` which also causes problems in a Windows Environment. It can be changed to use `System.IO.Path.DirectorySeparatorChar`

**Comment by sassembla** [comment]
Thank you for your information! I'll check it.

**Comment by sassembla** [comment]
actually, Directory.GetFiles() method returns these mixed path.  I've fixed it.
https://github.com/unity3d-jp/AssetGraph/commit/dfbf31b4320be96aaac3e2b6ed5bc3b9fd42c355

And so, because of Unity's Application.dataPath property returns '/' separated path like "C:/somewhere/project/Assets",
I'm using '/' for folder delimiter.
