### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by Munter** [unity3d-jp/AssetGraph#2]
I just want you to be aware that I have been working on a project called [assetgraph](https://github.com/assetgraph), which has existed for years. I can see that we're not targeting the same demographic. Never the less it would make things a lot easier for both projects if there wasn't any confusion about what project was just mentioned

**Comment by hiroki-o** [comment]
Hi, thank you for pinging us for project name clash. 

Regarding millions of software projects on earth today, name collision is unavoidable issue with almost any names. 
While our goal is to provide easy toolset to solve problems for developers, we prefer simple and straightforward name which describes project itself, rather than choosing exotic one - which makes us almost impossible to chose name which doesn't collide with someone. 

Luckily as you describe our project's target demographics does not overlap at all, so I believe we can coexist without inducing community confusion.  

Development-wise, we are still very early stage and we may change project name if we found more appropriate/straightforward name for us. But for now we will just keep the name.

**Comment by Munter** [comment]
Alright. Now we know. Good luck on your project :)
